/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RuleEngineService } from "../ruleEngine.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RuleEngineCreateInput } from "./RuleEngineCreateInput";
import { RuleEngine } from "./RuleEngine";
import { RuleEngineFindManyArgs } from "./RuleEngineFindManyArgs";
import { RuleEngineWhereUniqueInput } from "./RuleEngineWhereUniqueInput";
import { RuleEngineUpdateInput } from "./RuleEngineUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RuleEngineControllerBase {
  constructor(
    protected readonly service: RuleEngineService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RuleEngine })
  @nestAccessControl.UseRoles({
    resource: "RuleEngine",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRuleEngine(
    @common.Body() data: RuleEngineCreateInput
  ): Promise<RuleEngine> {
    return await this.service.createRuleEngine({
      data: {
        ...data,

        device: data.device
          ? {
              connect: data.device,
            }
          : undefined,
      },
      select: {
        action: true,
        condition: true,
        createdAt: true,

        device: {
          select: {
            id: true,
          },
        },

        id: true,
        ruleName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RuleEngine] })
  @ApiNestedQuery(RuleEngineFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RuleEngine",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ruleEngines(@common.Req() request: Request): Promise<RuleEngine[]> {
    const args = plainToClass(RuleEngineFindManyArgs, request.query);
    return this.service.ruleEngines({
      ...args,
      select: {
        action: true,
        condition: true,
        createdAt: true,

        device: {
          select: {
            id: true,
          },
        },

        id: true,
        ruleName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RuleEngine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RuleEngine",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ruleEngine(
    @common.Param() params: RuleEngineWhereUniqueInput
  ): Promise<RuleEngine | null> {
    const result = await this.service.ruleEngine({
      where: params,
      select: {
        action: true,
        condition: true,
        createdAt: true,

        device: {
          select: {
            id: true,
          },
        },

        id: true,
        ruleName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RuleEngine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RuleEngine",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRuleEngine(
    @common.Param() params: RuleEngineWhereUniqueInput,
    @common.Body() data: RuleEngineUpdateInput
  ): Promise<RuleEngine | null> {
    try {
      return await this.service.updateRuleEngine({
        where: params,
        data: {
          ...data,

          device: data.device
            ? {
                connect: data.device,
              }
            : undefined,
        },
        select: {
          action: true,
          condition: true,
          createdAt: true,

          device: {
            select: {
              id: true,
            },
          },

          id: true,
          ruleName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RuleEngine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RuleEngine",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRuleEngine(
    @common.Param() params: RuleEngineWhereUniqueInput
  ): Promise<RuleEngine | null> {
    try {
      return await this.service.deleteRuleEngine({
        where: params,
        select: {
          action: true,
          condition: true,
          createdAt: true,

          device: {
            select: {
              id: true,
            },
          },

          id: true,
          ruleName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
