/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DeviceService } from "../device.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeviceCreateInput } from "./DeviceCreateInput";
import { Device } from "./Device";
import { DeviceFindManyArgs } from "./DeviceFindManyArgs";
import { DeviceWhereUniqueInput } from "./DeviceWhereUniqueInput";
import { DeviceUpdateInput } from "./DeviceUpdateInput";
import { RuleEngineFindManyArgs } from "../../ruleEngine/base/RuleEngineFindManyArgs";
import { RuleEngine } from "../../ruleEngine/base/RuleEngine";
import { RuleEngineWhereUniqueInput } from "../../ruleEngine/base/RuleEngineWhereUniqueInput";
import { SensorFindManyArgs } from "../../sensor/base/SensorFindManyArgs";
import { Sensor } from "../../sensor/base/Sensor";
import { SensorWhereUniqueInput } from "../../sensor/base/SensorWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeviceControllerBase {
  constructor(
    protected readonly service: DeviceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Device })
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDevice(@common.Body() data: DeviceCreateInput): Promise<Device> {
    return await this.service.createDevice({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        status: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Device] })
  @ApiNestedQuery(DeviceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async devices(@common.Req() request: Request): Promise<Device[]> {
    const args = plainToClass(DeviceFindManyArgs, request.query);
    return this.service.devices({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        status: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Device })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async device(
    @common.Param() params: DeviceWhereUniqueInput
  ): Promise<Device | null> {
    const result = await this.service.device({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        status: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Device })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDevice(
    @common.Param() params: DeviceWhereUniqueInput,
    @common.Body() data: DeviceUpdateInput
  ): Promise<Device | null> {
    try {
      return await this.service.updateDevice({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          status: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Device })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDevice(
    @common.Param() params: DeviceWhereUniqueInput
  ): Promise<Device | null> {
    try {
      return await this.service.deleteDevice({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          status: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/ruleEngines")
  @ApiNestedQuery(RuleEngineFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RuleEngine",
    action: "read",
    possession: "any",
  })
  async findRuleEngines(
    @common.Req() request: Request,
    @common.Param() params: DeviceWhereUniqueInput
  ): Promise<RuleEngine[]> {
    const query = plainToClass(RuleEngineFindManyArgs, request.query);
    const results = await this.service.findRuleEngines(params.id, {
      ...query,
      select: {
        action: true,
        condition: true,
        createdAt: true,

        device: {
          select: {
            id: true,
          },
        },

        id: true,
        ruleName: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/ruleEngines")
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "update",
    possession: "any",
  })
  async connectRuleEngines(
    @common.Param() params: DeviceWhereUniqueInput,
    @common.Body() body: RuleEngineWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ruleEngines: {
        connect: body,
      },
    };
    await this.service.updateDevice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/ruleEngines")
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "update",
    possession: "any",
  })
  async updateRuleEngines(
    @common.Param() params: DeviceWhereUniqueInput,
    @common.Body() body: RuleEngineWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ruleEngines: {
        set: body,
      },
    };
    await this.service.updateDevice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/ruleEngines")
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "update",
    possession: "any",
  })
  async disconnectRuleEngines(
    @common.Param() params: DeviceWhereUniqueInput,
    @common.Body() body: RuleEngineWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ruleEngines: {
        disconnect: body,
      },
    };
    await this.service.updateDevice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/sensors")
  @ApiNestedQuery(SensorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "read",
    possession: "any",
  })
  async findSensors(
    @common.Req() request: Request,
    @common.Param() params: DeviceWhereUniqueInput
  ): Promise<Sensor[]> {
    const query = plainToClass(SensorFindManyArgs, request.query);
    const results = await this.service.findSensors(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,

        device: {
          select: {
            id: true,
          },
        },

        id: true,
        model: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/sensors")
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "update",
    possession: "any",
  })
  async connectSensors(
    @common.Param() params: DeviceWhereUniqueInput,
    @common.Body() body: SensorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sensors: {
        connect: body,
      },
    };
    await this.service.updateDevice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/sensors")
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "update",
    possession: "any",
  })
  async updateSensors(
    @common.Param() params: DeviceWhereUniqueInput,
    @common.Body() body: SensorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sensors: {
        set: body,
      },
    };
    await this.service.updateDevice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/sensors")
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "update",
    possession: "any",
  })
  async disconnectSensors(
    @common.Param() params: DeviceWhereUniqueInput,
    @common.Body() body: SensorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sensors: {
        disconnect: body,
      },
    };
    await this.service.updateDevice({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/device/status/:id")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetDeviceStatus(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.GetDeviceStatus(body);
  }
}
