/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SensorService } from "../sensor.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SensorCreateInput } from "./SensorCreateInput";
import { Sensor } from "./Sensor";
import { SensorFindManyArgs } from "./SensorFindManyArgs";
import { SensorWhereUniqueInput } from "./SensorWhereUniqueInput";
import { SensorUpdateInput } from "./SensorUpdateInput";
import { DataStreamFindManyArgs } from "../../dataStream/base/DataStreamFindManyArgs";
import { DataStream } from "../../dataStream/base/DataStream";
import { DataStreamWhereUniqueInput } from "../../dataStream/base/DataStreamWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SensorControllerBase {
  constructor(
    protected readonly service: SensorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sensor })
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSensor(@common.Body() data: SensorCreateInput): Promise<Sensor> {
    return await this.service.createSensor({
      data: {
        ...data,

        device: data.device
          ? {
              connect: data.device,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,

        device: {
          select: {
            id: true,
          },
        },

        id: true,
        model: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Sensor] })
  @ApiNestedQuery(SensorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sensors(@common.Req() request: Request): Promise<Sensor[]> {
    const args = plainToClass(SensorFindManyArgs, request.query);
    return this.service.sensors({
      ...args,
      select: {
        createdAt: true,
        description: true,

        device: {
          select: {
            id: true,
          },
        },

        id: true,
        model: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sensor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sensor(
    @common.Param() params: SensorWhereUniqueInput
  ): Promise<Sensor | null> {
    const result = await this.service.sensor({
      where: params,
      select: {
        createdAt: true,
        description: true,

        device: {
          select: {
            id: true,
          },
        },

        id: true,
        model: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sensor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSensor(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() data: SensorUpdateInput
  ): Promise<Sensor | null> {
    try {
      return await this.service.updateSensor({
        where: params,
        data: {
          ...data,

          device: data.device
            ? {
                connect: data.device,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,

          device: {
            select: {
              id: true,
            },
          },

          id: true,
          model: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sensor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSensor(
    @common.Param() params: SensorWhereUniqueInput
  ): Promise<Sensor | null> {
    try {
      return await this.service.deleteSensor({
        where: params,
        select: {
          createdAt: true,
          description: true,

          device: {
            select: {
              id: true,
            },
          },

          id: true,
          model: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/dataStreams")
  @ApiNestedQuery(DataStreamFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DataStream",
    action: "read",
    possession: "any",
  })
  async findDataStreams(
    @common.Req() request: Request,
    @common.Param() params: SensorWhereUniqueInput
  ): Promise<DataStream[]> {
    const query = plainToClass(DataStreamFindManyArgs, request.query);
    const results = await this.service.findDataStreams(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        sensor: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dataStreams")
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "update",
    possession: "any",
  })
  async connectDataStreams(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() body: DataStreamWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataStreams: {
        connect: body,
      },
    };
    await this.service.updateSensor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dataStreams")
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "update",
    possession: "any",
  })
  async updateDataStreams(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() body: DataStreamWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataStreams: {
        set: body,
      },
    };
    await this.service.updateSensor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dataStreams")
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "update",
    possession: "any",
  })
  async disconnectDataStreams(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() body: DataStreamWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataStreams: {
        disconnect: body,
      },
    };
    await this.service.updateSensor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/sensor/data/:id")
  @swagger.ApiOkResponse({
    type: Sensor,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetSensorData(
    @common.Body()
    body: string
  ): Promise<Sensor[]> {
    return this.service.GetSensorData(body);
  }
}
